server:
  port: 9999
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Liu2002420
    url: jdbc:mysql://localhost:3306/db_blogs?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  data:
    redis:
      host: 127.0.0.1
      port: 6379

mybatis:
  mapper-locations: classpath:sys/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.doubao: debug
